#!/bin/bash

# Initialize a total sum variable
total_sum=0

read -p "Enter username:" usern
read -p "Enter Start Date: " sd
read -p "Enter End Date: " ed

sacct -r IllinoisComputes-GPU -u $usern -S $sd -E $ed -s COMPLETED -o ElapsedRaw,ReqTRES -X -n > list

while read -r line; do
    # Extract the first number (before "billing=")
    first_num=$(echo "$line" | awk '{print $1}')

    # Extract the number after "billing="
    second_num=$(echo "$line" | grep -oP '(?<=billing=)\d+')

    # Multiply the two numbers
    product=$((first_num * second_num))

    # Add the product to the total sum
    total_sum=$((total_sum + product))

#done < "${1:-/dev/stdin}"
done < list

# Divide the total sum by 360
final_result=$(echo "scale=2; $total_sum / 360" | bc)

# Output the final result
echo "You have used $final_result GPU hours"

rm -f list
