#!/bin/bash

echo "Enter dates in YYYY-MM-DD format."

read -p "Enter Start Date: " sd
read -p "Enter End Date: " ed
read -p "Enter the partition name: " pn

sacct -r $pn -o cputimeraw -S $sd -E $ed -s COMPLETED > jobs.out
awk '{ sum += $1 } END { print sum }' jobs.out >> jobhours.out
awk '{print $1 / 3600}' jobhours.out >> jobstotal
cat jobstotal
echo "CPU Hours used by $pn between $sd and $ed"

rm -f job*
