#!/bin/bash

echo "Before doing this, have you"
echo "Added the 3 DNS Entries to NetDot and added the node to Puppet???"

# Prompt the user for nodename
read -p "Enter nodename: " nodename
read -p "Enter BMC IP: " bmcip
read -p "Enter MGMT IP: " mgmtip
read -p "Enter mac address: " macaddress
read -p "Enter public IP: " publicip

echo "Processing node: $nodename"

# ssh $nodename "hostname"
mkdef $nodename groups=compute,physical,all
chdef $nodename nicdevices.hsn0.1840=hsn0
chdef $nodename nichostnamesuffixes.hsn0.1840=-hsn0-1840
chdef $nodename nicnetworks.hsn0.1840=public_net
chdef $nodename nictypes.hsn0.1840=vlan
chdef $nodename nictypes.hsn0=Ethernet
chdef $nodename nicips.hsn0.1840=$publicipdd
chdef $nodename ip=$bmcip
chdef $nodename bmc=$bmcip
chdef $nodename mac=$macaddress

imagename=rhels9.4.0-x86_64-netboot-rh94base250108
echo "using image $imagename"
read -p "Is using $imagename good? (y/n): " response

# Check user response
if [ "$response" != "y" ]; then
    echo "Exiting script."
    exit 1
fi
nodeset $nodename $imagename

makedhcp -a
makedhcp -n
makehosts

exit 0
