#!/bin/bash

print_used_vfs() {
    echo -e "VM ID\tName\t\tHostPCI"
    while read -r vmid name _; do
        hostpci=$(qm config "$vmid" | grep '^hostpci')
        if [ -n "$hostpci" ]; then
            while read -r line; do
                echo -e "$vmid\t$name\t\t$line"
            done <<< "$hostpci"
        fi
    done < <(qm list | awk 'NR>1 {print $1, $2}')
}

print_all_vfs() {
    lspci | grep "Virtual Function"
}

print_available_vfs() {
    all_vfs=$(lspci | grep "Virtual Function" | awk '{print $1}' | sed 's/^0000://')

    used_pci=$(for vmid in $(qm list | awk 'NR>1 {print $1}'); do
        qm config "$vmid" | awk '/^hostpci/ {print $2}' | cut -d, -f1 | sed 's/^0000://'
    done)

    echo "Available Virtual Functions:"
    for vf in $all_vfs; do
        if ! echo "$used_pci" | grep -qi "$vf"; then
            echo "$vf"
        fi
    done
}

print_vf_log() {
    echo "Historical VF mapping log entries:"
    grep -i hostpci /var/log/syslog 2>/dev/null || echo "No entries found or /var/log/syslog not present"
}

usage() {
    echo "Usage: $0 [OPTION]"
    echo "Options:"
    echo "  -u, --used     Show VFs currently assigned to VMs"
    echo "  -f, --all      Show all Virtual Functions on the host"
    echo "  -a, --avail    Show unassigned Virtual Functions"
    echo "  -l, --log      Show historical VF mapping entries from syslog"
    echo "  -h, --help     Display this help message"
    exit 0
}

if [ $# -eq 0 ]; then
    usage
fi

while [[ "$#" -gt 0 ]]; do
    case "$1" in
        -u|--used)
            print_used_vfs
            ;;
        -f|--all)
            print_all_vfs
            ;;
        -a|--avail)
            print_available_vfs
            ;;
        -l|--log)
            print_vf_log
            ;;
        -h|--help)
            usage
            ;;
        -*)
            echo "Unknown option: $1"
            usage
            ;;
    esac
    shift
done
