#!/bin/bash

#Grab the PCI address of the Mellanox NIC
devname=$(lspci | grep -i 'Mellanox' | awk '{print $1}')

#Check to see if one exists
if [[ -z "$devname" ]]; then
    exit 1
fi

line_count=$(mstconfig -d "$mellanoxdevname" query | grep LINK_TYPE | wc -l)

#Set the link type to ethernet.

if ["$line_count" -gt 1]; then
    echo "y" | mstconfig -d "$devname" set LINK_TYPE_P1=ETH LINK_TYPE_P2=ETH > /dev/null 2>&1
else
    echo "y" | mstconfig -d "$devname" set LINK_TYPE_P1=ETH > /dev/null 2>&1

reboot
